/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Interface_acceuil (void);
GtkWidget* create_Interface_agent (void);
GtkWidget* create_Interface_admin (void);
GtkWidget* create_Interface_client (void);
GtkWidget* create_login (void);
GtkWidget* create_Catalogue_interfaceClient (void);
GtkWidget* create_reserver_interfaceclient (void);
GtkWidget* create_mafficher (void);
GtkWidget* create_apropos (void);
GtkWidget* create_majouter (void);
