/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Interface_acceuil;
  GtkWidget *Interface_agent;
  GtkWidget *Interface_admin;
  GtkWidget *interface_client;
  GtkWidget *login;
  int id_rec;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Interface_acceuil = create_Interface_acceuil ();
  gtk_widget_show (Interface_acceuil);
 /* Interface_agent = create_Interface_agent ();
  gtk_widget_show (Interface_agent);
  Interface_admin = create_Interface_admin ();
  gtk_widget_show (Interface_admin);
  interface_client = create_interface_client ();
  gtk_widget_show (interface_client);
  login = create_login ();
  gtk_widget_show (login); */

  gtk_main ();
  return 0;
}

